"""added the is verified field

Revision ID: 523aab06c2b5
Revises: 48242dadac1e
Create Date: 2025-12-25 21:17:23.733671

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "523aab06c2b5"
down_revision: Union[str, Sequence[str], None] = "48242dadac1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "isverified", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "isverified")
    # ### end Alembic commands ###
